test-mymath: test.o giaithua.o tongchan.o tongle.o luythua.o
	gcc -o test-mymath test.o giaithua.o tongchan.o tongle.o luythua.o
test: test.c libmymath.h
	gcc -c test.c
giaithua.o: giaithua.c
	gcc -c giaithua.c
tongchan.o: tongchan.c
	gcc -c tongchan.c
tongle.o: tongle.c
	gcc -c tongle.c
luythua.o: luythua.c
	gcc -c luythua.c

